
161218A:
     trigger_time: 1482032854.75
     joint_detectors: ['BAT']
     polar_src_interval: ['0.0-7.2']
     polar_bkg_intervals: ['-30.0--5.0','20-80']
     polar_unbinned_bkg:
     polar_active_interval: ['45-750']
     joint_src_interval: 
     joint_bkg_intervals: []
     joint_active_measurement: ["15-350"]
     constspec_lo: 0.7
     constspec_hi: 1.3
     constpol_lo: 0.7
     constpol_hi: 1.5
     gbm_source_name: 
     gbm_trigger_id: 
     swift_file: "sw00727288000b_avg"
     spec_prior: "Band"

170127C:
     trigger_time: 1485480947.7500
     joint_detectors: ['n1', 'n2', 'n5', 'b1']
     polar_src_interval: ['-0.1-0.2']
     polar_bkg_intervals: ['-50--5','40-100']
     polar_unbinned_bkg: False
     polar_active_interval: ['30-750']
     joint_src_interval: ['-0.1-0.2']
     joint_bkg_intervals: ['-50--5','40-100']
     joint_active_measurement: ['8.1-510', '8.1-510', '8.1-510', '300-35000']
     constspec_lo: 0.5
     constspec_hi: 1.3
     constpol_lo: 0.5
     constpol_hi: 1.5
     gbm_source_name: 'GRB170127067'
     gbm_trigger_id: 'bn170127067'
     swift_file: 
     spec_prior: "CPL"


170305A:
     trigger_time: 1488694146.7500
     joint_detectors: ['n1', 'n2', 'b0'] # removed n0 detector even though that is recommended since its file is corrupt
     polar_src_interval: ['0.0-0.3']
     polar_bkg_intervals: ['-80.0--5.0','10-100']
     polar_unbinned_bkg: False
     polar_active_interval: ['30-750']
     joint_src_interval: ['0.0-0.3']
     joint_bkg_intervals: ['-50--5','50-100']
     joint_active_measurement: ['8.1-510', '8.1-510', '8.1-510', '300-35000']
     constspec_lo: 0.7
     constspec_hi: 1.3
     constpol_lo: 0.7
     constpol_hi: 1.5
     gbm_source_name: 'GRB170305256'
     gbm_trigger_id: 'bn170305256'
     swift_file: 
     spec_prior: "Band"
170101A:
     trigger_time: 1483237560.67900
     joint_detectors: ['BAT']
     polar_src_interval: ['0.0-3.104']
     polar_bkg_intervals: ['-100.0--5.0','25-75']
     polar_unbinned_bkg:
     polar_active_interval: ['40-750']
     joint_src_interval: 
     joint_bkg_intervals: []
     joint_active_measurement: ["15-350"]
     constspec_lo: 0.7
     constspec_hi: 1.3
     constpol_lo: 0.7
     constpol_hi: 1.5
     gbm_source_name: 
     gbm_trigger_id: 
     swift_file: "sw00729293000b_avg"
     spec_prior: "CPL"

161229A:
     trigger_time: 1483045428.8200
     joint_detectors: ['n9', 'na', 'nb', 'b1']
     polar_src_interval: ['-5.0-40.0']
     polar_bkg_intervals: ['-50--10','45-100']
     polar_unbinned_bkg:
     polar_active_interval: ['30-750']
     joint_src_interval: ['-5.0-40.0']
     joint_bkg_intervals: ['-50--10','45-100']
     joint_active_measurement: ['8.1-510', '8.1-510', '8.1-510', '300-35000']
     constspec_lo: 0.7
     constspec_hi: 1.3
     constpol_lo: 0.7
     constpol_hi: 1.5
     gbm_source_name: 'GRB161229878'
     gbm_trigger_id: 'bn161229878'
     swift_file: 
     spec_prior: "Band"


170320A:
     trigger_time: 1489981359.0000
     joint_detectors: []
     polar_src_interval: ['0-12.0']
     polar_bkg_intervals: ['-25.0--5.0','15-25']
     polar_unbinned_bkg:
     polar_active_interval: ['30-750']
     joint_src_interval: 
     joint_bkg_intervals: []
     joint_active_measurement: []
     constspec_lo: 
     constspec_hi: 
     constpol_lo: 0.5
     constpol_hi: 1.5
     gbm_source_name: 
     gbm_trigger_id: 
     swift_file: 
     spec_prior: "Band"

161217C:
     trigger_time: 1481946795.0000
     joint_detectors: []
     polar_src_interval: ['-5.0-4.5']
     polar_bkg_intervals: ['-50.0--10.0','10-50']
     polar_unbinned_bkg:
     polar_active_interval: ['30-750']
     joint_src_interval: 
     joint_bkg_intervals: []
     joint_active_measurement: []
     constspec_lo:
     constspec_hi:
     constpol_lo: 0.7
     constpol_hi: 1.5
     gbm_source_name: 
     gbm_trigger_id: 
     swift_file: 
     spec_prior: "Band"

170101B:
     trigger_time: 1483238838.2700
     joint_detectors: ['n9', 'na', 'nb', 'b1']
     polar_src_interval: ['-1.0-15.0']
     polar_bkg_intervals: ['-100.0--5.0','25-75']
     polar_unbinned_bkg:
     polar_active_interval: ['30-750']
     joint_src_interval: ['-1.0-15.0']
     joint_bkg_intervals: ['-50--5','50-100']
     joint_active_measurement: ['8.1-510', '8.1-510', '8.1-510', '300-35000']
     constspec_lo: 0.7
     constspec_hi: 1.3
     constpol_lo: 0.7
     constpol_hi: 1.5
     gbm_source_name: 'GRB170101116'
     gbm_trigger_id: 'bn170101116'
     swift_file: 
     spec_prior: "Band"




170206A:
     trigger_time: 1486378317.4000
     joint_detectors: ['n8', 'n9', 'na', 'b1']
     polar_src_interval: ['0.0-2.0']
     polar_bkg_intervals: ['-50--5','5-100']
     polar_unbinned_bkg:
     polar_active_interval: ['30-750']
     joint_src_interval: ['-0.3-1.7']
     joint_bkg_intervals: ['-50--5','50-100']
     joint_active_measurement: ['8.1-510', '8.1-510', '8.1-510', '300-35000']
     constspec_lo: 0.5
     constspec_hi: 1.3
     constpol_lo: 0.5
     constpol_hi: 1.5
     gbm_source_name: 'GRB170206453'
     gbm_trigger_id: 'bn170206453'
     swift_file: 
     spec_prior: "Band"



170207A:
     trigger_time: 1486503903.6700
     joint_detectors: ['n1', 'n2', 'n5', 'b0']
     polar_src_interval: ['0.0-25.0','37.0-44.0']
     polar_bkg_intervals: ['-80.0--10.0','45-100']
     polar_unbinned_bkg: False
     polar_active_interval: ['30-750']
     joint_src_interval: ['0.0-25.0','37.0-44.0']
     joint_bkg_intervals: ['-80.0--10.0','45-80']
     joint_active_measurement: ['8.1-510', '8.1-510', '8.1-510', '300-35000']
     constspec_lo: 0.5
     constspec_hi: 1.3
     constpol_lo: 0.5
     constpol_hi: 1.5
     gbm_source_name: 'GRB170207906'
     gbm_trigger_id: 'bn170207906'
     swift_file: 
     spec_prior: "Band"



170210A:
     trigger_time: 1486694856.5800
     joint_detectors: ['n2', 'n5', 'na', 'b0']
     polar_src_interval: ['30.0-100.0']
     polar_bkg_intervals: ['-50--5','110-200']
     polar_unbinned_bkg: False
     polar_active_interval: ['30-750']
     joint_src_interval: ['30.0-100.0']
     joint_bkg_intervals: ['-50--5','110-200']
     joint_active_measurement: ['8.1-510', '8.1-510', '8.1-510', '300-35000']
     constspec_lo: 0.5
     constspec_hi: 1.3
     constpol_lo: 0.5
     constpol_hi: 1.5
     gbm_source_name: 'GRB170210116'
     gbm_trigger_id: 'bn170210116'
     swift_file: 
     spec_prior: "Band"



170114A:
     trigger_time: 1484431269.5000
     joint_detectors: ['n1', 'n5', 'n8', 'b0']
     polar_src_interval: ['-0.2-8.9']
     polar_bkg_intervals: ['-35--10', '25-75']
     polar_unbinned_bkg:
     polar_active_interval: ['30-750']
     joint_src_interval: ['-0.2-8.9']
     joint_bkg_intervals: ['-50--5', '15-100']
     joint_active_measurement: ['8.1-510', '8.1-510', '8.1-510', '300-35000']
     constspec_lo: 0.7
     constspec_hi: 1.4
     constpol_lo: 0.7
     constpol_hi: 1.6
     gbm_source_name: 'GRB170114917'
     gbm_trigger_id: 'bn170114917'
     swift_file: 
     spec_prior: "Band"

161218B:
     trigger_time: 1482049960.6500
     joint_detectors: ['n3', 'n7', 'n8', 'b0']
     polar_src_interval: ['0.0-30.0']
     polar_bkg_intervals: ['-40.0--12.0','60-110']
     polar_unbinned_bkg: False
     polar_active_interval: ['40-700']
     joint_src_interval: ['0.0-30.0']
     joint_bkg_intervals: ['-80.0--10.0','50-100']
     joint_active_measurement: ['8.1-510', '8.1-510', '8.1-510', '300-35000']
     constspec_lo: 0.7
     constspec_hi: 1.5
     constpol_lo: 0.7
     constpol_hi: 1.5
     gbm_source_name: 'GRB161218356'
     gbm_trigger_id: 'bn161218356'
     swift_file: 
     spec_prior: "Band"


